spring:
  datasource:
    url: jdbc:mysql://gunni-identifier.c96ms6m44sen.ap-northeast-2.rds.amazonaws.com:3306/gunniDatabase
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gunni_user
    password: gunni1234!

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

application:
  jwt:
    refresh-exp: 2592000000 #30?
    access-exp: 86400000 # 24??
    prefix: Bearer
    header: Authorization
    secretKey: f604246c7b7cfc1cbbe766d3e50cd56f3ef15608ef1b5fc194ebc468b683932b

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs

  default-consumes-media-type: application/json
  auto-tag-classes: true
  groups:
    enabled: false

  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html